<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\RelationsBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/bundles/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class EserviceGroupRepository extends EntityRepository {

     protected $query;

    private function myFindJoin() {
        $values = array('a,b');           
          //$values = array('a,partial b.{id,username}');           
        $query = $this->createQueryBuilder('a')
                ->select($values)
                ->leftJoin('a.users', 'b')
            
        ;
        return ($query);
    }

    public function myFindAll() {

         $this->query = $this->myFindJoin();
        $query = $this->query
       
                ->add('orderBy', 'a.id DESC')
           /*     ->where('a.proprietaire = :proprietaire')
                ->leftJoin('a.proprietaire', 'b')
                ->leftJoin('a.categorie', 'c')
                ->leftJoin('a.idStatus', 'd')
                 ->setParameter('proprietaire', $user_id)*/
                ->getQuery();

        return $query;

    }

 
}