services:
   application_relations_twig_extension:
        class: Application\RelationsBundle\Twig\Extensions\ApplicationRelationsExtension
        tags:
            - { name: twig.extension }
            
    